from django.urls import path, include
from rest_framework.routers import DefaultRouter
from kanbanapi.views import UserRegistrationView, UserLoginView, UserProfileView, TaskCardViewSet, HabitListViewSet, HabitTrackerViewSet

router = DefaultRouter()
router.register(r'tasks', TaskCardViewSet, basename='taskcard') # Register TaskCardViewSet with router
router.register(r'habits', HabitListViewSet, basename='habit') # <---- Register HabitListViewSet with router
router.register(r'habittrackers', HabitTrackerViewSet, basename='habittracker') # <---- Register HabitTrackerViewSet




urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'), # URL for user registration
    path('login/', UserLoginView.as_view(), name='login'),       # URL for user login
    path('user/profile/', UserProfileView.as_view(), name='user-profile'), # ADD THIS LINE for user profile endpoint
    path('', include(router.urls)), # Include URLs generated by the router
]