from django.urls import path, include
from rest_framework.routers import DefaultRouter
from kanbanapi.views import UserRegistrationView, UserLoginView, UserProfileView, TaskCardViewSet, HabitListViewSet, HabitTrackerViewSet, EventViewSet, TodayJournalEntryView, JournalEntryListView, BadgeListView, UserBadgeListView


router = DefaultRouter()
router.register(r'tasks', TaskCardViewSet, basename='taskcard') # Register TaskCardViewSet with router
router.register(r'habits', HabitListViewSet, basename='habit') # <---- Register HabitListViewSet with router
router.register(r'habittrackers', HabitTrackerViewSet, basename='habittracker') # <---- Register HabitTrackerViewSet
router.register(r'events', EventViewSet, basename='event')



urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'), # URL for user registration
    path('login/', UserLoginView.as_view(), name='login'),       # URL for user login
    path('user/profile/', UserProfileView.as_view(), name='user-profile'), # ADD THIS LINE for user profile endpoint
    path('journalentries/today/', TodayJournalEntryView.as_view(), name='today-journal-entry'),
    path('journalentries/', JournalEntryListView.as_view(), name='journal-list'), # URL for listing all journal entries
    path('badges/', BadgeListView.as_view(), name='badge-list'), # URL for listing all badges - accessible at /api/badges/
    path('users/badges/', UserBadgeListView.as_view(), name='user-badge-list'), # NEW URL for user badges
    path('', include(router.urls)), # Include URLs generated by the router
]