# Generated by Django 5.1.6 on 2025-02-28 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapi', '0003_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Briefly describe the task.', max_length=200, verbose_name='Task Title')),
                ('summary', models.TextField(blank=True, help_text='Detailed description or notes for the task (optional).', null=True, verbose_name='Summary')),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('processing', 'Processing'), ('done', 'Done')], default='to_do', help_text='Current status of the task.', max_length=20, verbose_name='Status')),
                ('task_type', models.CharField(choices=[('personal', 'Personal'), ('professional', 'Professional'), ('educational', 'Educational/Learning'), ('health_wellness', 'Health & Wellness'), ('financial', 'Financial'), ('other', 'Other')], default='other', help_text='Category of the task.', max_length=50, verbose_name='Type')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Priority level of the task.', max_length=20, verbose_name='Priority')),
                ('due_date', models.DateField(blank=True, help_text='Optional date by which the task should be completed.', null=True, verbose_name='Due Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
