# Generated by Django 5.1.6 on 2025-03-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapi', '0006_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
