# Generated by Django 5.1.6 on 2025-03-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapi', '0008_journalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Badge Title')),
                ('description', models.TextField(verbose_name='Badge Description')),
                ('criteria', models.TextField(help_text='Detailed criteria for earning this badge (for admin reference).', verbose_name='Badge Criteria')),
                ('badge_type', models.CharField(choices=[('task', 'Task'), ('habit', 'Habit'), ('schedule', 'Schedule'), ('journal', 'Journal'), ('general', 'General')], default='general', max_length=20, verbose_name='Badge Type')),
                ('icon', models.CharField(help_text='File path to the badge icon image (e.g., "badges/organized.png").', max_length=255, verbose_name='Badge Icon File Path')),
            ],
        ),
    ]
