# Generated by Django 5.1.6 on 2025-03-24 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanbanapi", "0010_userbadge"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskcard",
            name="is_event",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this task is related to a scheduled event.",
                verbose_name="Is Related to Event",
            ),
        ),
        migrations.AddField(
            model_name="taskcard",
            name="is_habit",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this task is a daily habit.",
                verbose_name="Is Habit",
            ),
        ),
        migrations.AddField(
            model_name="taskcard",
            name="related_event",
            field=models.ForeignKey(
                blank=True,
                help_text="The event this task is related to (optional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_tasks",
                to="kanbanapi.event",
                verbose_name="Related Event",
            ),
        ),
    ]
