# Generated by Django 5.1.6 on 2025-03-26 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanbanapi", "0011_taskcard_is_event_taskcard_is_habit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskcard",
            name="habit_tracker",
            field=models.ForeignKey(
                blank=True,
                help_text="The Habit Tracker entry associated with this task (for habit tasks).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_card",
                to="kanbanapi.habittracker",
                verbose_name="Related Habit Tracker Entry",
            ),
        ),
    ]
