# Generated by Django 5.1.6 on 2025-04-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanbanapi", "0012_taskcard_habit_tracker"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="habit_streak",
            field=models.IntegerField(
                default=0,
                help_text="Current consecutive days of habit completion.",
                verbose_name="Habit Streak",
            ),
        ),
    ]
